name: deploy

on:
  push:
    branches:
      - master

env:
  AZURE_FUNCTIONAPP_NAME: bazos-updater

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout folder
        uses: actions/checkout@v2

      - name: 'Deploy to Azure'
        uses: Azure/functions-action@v1
        id: fa
        env:
          ENABLE_ORYX_BUILD: true
          SCM_DO_BUILD_DURING_DEPLOYMENT: true
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
